blog/urls.py
# -*- coding: utf-8 -*-
# @Time    : 19-1-11 下午1:57
# @Author  : Nick
# @Email   : haijun0422@126.com
# @File    : urls.py
# @Software: PyCharm
from django.urls import path, re_path
from . import views
app_name = 'blog'
urlpatterns = [
    # 所有文章列表
    path('', views.ArticleListView.as_view(), name='article_list'),
    # 展示文章详情
    re_path(r'^article/(?P<pk>\d+)/(?P<slug1>[-\w]+)/$', views.ArticleDetailView.as_view(), name='article_detail'),
    # 草稿箱
    path('draft/', views.ArticleDraftListView.as_view(), name='article_draft_list'),
    # 已发表文章列表(含编辑)
    path('admin/', views.PublishedArticleListView.as_view(), name='published_article_list'),
    # 更新文章-
    re_path(r'^article/(?P<pk>\d+)/(?P<slug1>[-\w]+)/update/$', views.ArticleUpdateView.as_view(),
            name='article_update'),
    # 创建文章
    re_path(r'^article/create/$', views.ArticleCreateView.as_view(), name='article_create'),
    # 发表文章登录
    re_path(r'^article/(?P<pk>\d+)/(?P<slug1>[-\w]+)/publish/$', views.article_publish, name='article_publish'),
    # 删除文章
    re_path(r'^article/(?P<pk>\d+)/(?P<slug1>[-\w]+)/delete$', views.ArticleDeleteView.as_view(),
            name='article_delete'),
    # 展示类别列表
    # re_path(r'^category/$', views.CategoryListView.as_view(), name='category_list'),
    # # 展示类别详情
    # re_path(r'^category/(?P<slug>[-\w]+)/$', views.CategoryDetailView.as_view(), name='category_detail'),
    # # 展示Tag详情
    # re_path(r'^tags/(?P<slug>[-\w]+)/$', views.TagDetailView.as_view(), name='tag_detail'),
    # # 搜索文章
    # re_path(r'^search/$', views.article_search, name='article_search'),
]

project_blog/urls.py
from django.contrib import admin
# from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url('admin/', admin.site.urls),
    url('^accounts/', include('allauth.urls')),
    url(r'^blog/', include('blog.urls')),
    # url(settings.MEDIA_ROOT, document_root=settings.MEDIA_ROOT),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/article_create_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "base.html" %}

{% block content %}


<h3>添加新文章</h3>

<form method="POST" class="form-horizontal" role="form" action="" >
  {% csrf_token %}

  {% for hidden_field in form.hidden_fields %}
    {{ hidden_field }}
  {% endfor %}

  {% if form.non_field_errors %}
    <div class="alert alert-danger col-md-12" role="alert">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>
  {% endif %}

  {% for field in form.visible_fields %}
  <div class="form-group col-md-12">
        {{ field.label_tag }}
        {{ field }}
        {% if field.errors %}
          {% for error in field.errors %}
            <div class="invalid-feedback">
              {{ error }}
            </div>
          {% endfor %}
        {% endif %}
      {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text }}</small>

      {% endif %}
    </div>
  {% endfor %}
  <div class="form-group">
     <div class="col-md-12">
    <input type="submit" class="btn btn-primary form-control" value="提交">
     </div>
  </div>
</form>

{% endblock %}

</body>
</html>

templates/article_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "base.html" %}

{% block content %}

<p>类别:
    {% if article.category.parent_category %}
<a href="{% url 'blog:category_detail' article.category.parent_category.slug %}">{{ article.category.parent_category.name }}</a> /
   {% endif %}
<a href="{% url 'blog:category_detail' article.category.slug %}">{{ article.category }}</a>
</p>


<h3>{{ article.title }}
    {% if article.status == "d" %}
    (草稿)
    {% endif %}
</h3>
 {% if article.status == "p" %}
<p>发布于{{ article.pub_date | date:"Y-m-d" }}      浏览{{ article.views }}次</p>
{% endif %}
<p>{{ article.body }}</p>
<p>标签:
    {% for tag in article.tags.all %}
    <a href="{% url 'blog:tag_detail' tag.slug %}">{{ tag.name }}</a>,
    {% endfor %}
</p>

{% if article.author == request.user %}
     {% if article.status == "d" %}
<a href="{% url 'blog:article_publish' article.id article.slug %}">发布</a> |
    {% endif %}<a href="{% url 'blog:article_update' article.id article.slug %}">编辑</a> |
<a href="{% url 'blog:article_delete' article.id article.slug %}">删除</a>
{% endif %}

{% endblock %}

</body>
</html>

templates/article_draft_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/article_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "base.html" %}

{% block content %}

<p>类别:
    {% if article.category.parent_category %}
<a href="{% url 'blog:category_detail' article.category.parent_category.slug %}">{{ article.category.parent_category.name }}</a> /
   {% endif %}
<a href="{% url 'blog:category_detail' article.category.slug %}">{{ article.category }}</a>
</p>


<h3>{{ article.title }}
    {% if article.status == "d" %}
    (草稿)
    {% endif %}
</h3>
 {% if article.status == "p" %}
<p>发布于{{ article.pub_date | date:"Y-m-d" }}      浏览{{ article.views }}次</p>
{% endif %}
<p>{{ article.body }}</p>
<p>标签:
    {% for tag in article.tags.all %}
    <a href="{% url 'blog:tag_detail' tag.slug %}">{{ tag.name }}</a>,
    {% endfor %}
</p>

{% if article.author == request.user %}
     {% if article.status == "d" %}
<a href="{% url 'blog:article_publish' article.id article.slug %}">发布</a> |
    {% endif %}<a href="{% url 'blog:article_update' article.id article.slug %}">编辑</a> |
<a href="{% url 'blog:article_delete' article.id article.slug %}">删除</a>
{% endif %}

{% endblock %}

</body>
</html>
</body>
</html>

templates/article_update_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

templates/published_article_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "base.html" %}

{% block content %}
<h3>已发表文章</h3>
{# 注释: page_obj不要改。Article可以改成自己对象 #}


<form action="{% url 'blog:article_search' %}" role="search" method="get">
    {% csrf_token %}
    <div class="input-group col-md-12">
        <input type="text" name="q" id="q" class="form-control" placeholder="搜索文章">
        <span class="input-group-btn">
            <button class="btn btn-default form-control" type="submit" value="submit">
                <span class="glyphicon glyphicon-search"></span>
            </button>
        </span>
        </div>
</form>

{% if page_obj %}
<table class="table table-striped">
    <thead>
        <tr>
            <th>标题</th>
            <th>类别</th>
            <th>发布日期</th>
            <th>查看</th>
            <th>修改</th>
            <th>删除</th>
        </tr>
    </thead>
    <tbody>
     {% for article in page_obj %}
        <tr>
            <td>
            {{ article.title }}
            </td>
            <td>
            {{ article.category.name }}
            </td>
            <td>
            {{ article.pub_date | date:"Y-m-d" }}
            </td>
             <td>
                 <a href="{% url 'blog:article_detail' article.id article.slug %}"><span class="glyphicon glyphicon-eye-open"></span></a>
            </td>

             <td>
                <a href="{% url 'blog:article_update' article.id article.slug %}"><span class="glyphicon glyphicon-wrench"></span></a>
            </td>

             <td>
                <a href="{% url 'blog:article_delete' article.id article.slug %}"><span class="glyphicon glyphicon-trash"></span></a>
            </td>
     {% endfor %}
        </tr>
    </tbody>
</table>

{% else %}
{# 注释: 这里可以换成自己的对象 #}
    <p>没有文章。</p>

{% endif %}


{# 注释: 下面代码一点也不要动 #}
{% if is_paginated %}
     <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
    {% else %}
      <li class="page-item disabled"><span class="page-link">Previous</span></li>
    {% endif %}

    {% for i in paginator.page_range %}
        {% if page_obj.number == i %}
      <li class="page-item active"><span class="page-link"> {{ i }} <span class="sr-only">(current)</span></span></li>
       {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
       {% endif %}
    {% endfor %}

         {% if page_obj.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
    {% else %}
      <li class="page-item disabled"><span class="page-link">Next</span></li>
    {% endif %}
    </ul>

{% endif %}

{% endblock %}
</body>
</html>